<?php echo $this->doctype() ?>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Invoicer: Login</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/global.css" rel="stylesheet">
</head>
<body>
<?php echo $this->layout()->content ?>
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</body>
</html>
